name: Publish

on:
  push:
    branches: [ main ]
env:
  DOTNET_VERSION: '6.0.x'
permissions:
  contents: write
jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['windows']
        include:
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        shell: bash
        run: |
          release_name="avttool-${{ matrix.target }}"

          # Build everything
          dotnet publish --framework net6.0 --runtime "${{ matrix.target }}" -c Release -o "$release_name"

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
          tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          # Delete output directory
          rm -r "$release_name"
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'
          prev_release_tag: "main"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          release_name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
          files: "avttool*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
